# Generated by Django 3.1.3 on 2020-11-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Клиент'), (2, 'Менеджер')], default=1),
        ),
    ]
